### ISSUE TITLE
Android 11 Support

### ISSUE THREAD

**Issue by kael-moreno** [ajayasija23/FilePicker#2]
Hi!

I tested your library in Android 11 and when trying to retrieve a pdf file, it crashes.

Here's the error log:

`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/document:39 flg=0x1 }} to activity {com.interactivex.kotlin.android.debug/com.interactivex.kotlin.android.ui.activity.dashboard.DashboardActivity}: java.lang.NullPointerException: FileUtils.getFile(this, data?.data) must not be null`

`Caused by: java.lang.NullPointerException: FileUtils.getFile(this, data?.data) must not be null`

It works for images and videos in Android 11 and it works for Android 10 (I assume older Android versions as well) with images, videos, pdfs.

I used */* and application/* MimeType as well. But still doesn't work with Android 11 when trying to retrieve non-media files.

Thank you!

**Comment by ajayasija23** [comment]
It Support Max Android Version 10

**Comment by kael-moreno** [comment]
Noted. Thank you!
